# Create a Data Frame with Pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
data = np.random.random(size=(5,3))
print(data)
df=pd.DataFrame(data=data, columns=["A","B","C"])
df

[[0.9241892  0.64287305 0.47445599]
 [0.89722556 0.63887507 0.9527099 ]
 [0.53175944 0.58596085 0.86265643]
 [0.35246907 0.85994335 0.44675591]
 [0.95977781 0.25160671 0.81467361]]


A         B         C
0  0.924189  0.642873  0.474456
1  0.897226  0.638875  0.952710
2  0.531759  0.585961  0.862656
3  0.352469  0.859943  0.446756
4  0.959778  0.251607  0.814674

In [5]:
df=pd.DataFrame(data={"A":[1,2,3], "B":["Sam", "Alex","John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [7]:
dtype=[("A",np.int),("B",(np.str,20))]
data=np.array([(1,"sam"),(2,"Alex"),(3,"John")], dtype=dtype)
print(data.dtype)


[('A', '<i4'), ('B', '<U20')]


In [9]:
df=pd.DataFrame(data)
df

A     B
0  1   sam
1  2  Alex
2  3  John

In [11]:
data=[{"A":1, "B":"Sam"},{"A":2, "B":"John"},{"A":3, "B":"Alex"}]
df=pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  John
2  3  Alex